from __future__ import annotations

from enum import IntEnum

from hikari import Color

from bot.infisical import Infisical

VERSION = "4.0"
MAX_CONTENT_LENGTH = 1000
ERROR_COLOR = Color.of((214, 48, 49))
REJECTED_COLOR = Color.of((207, 0, 15))
APPROVED_COLOR = Color.of((0, 230, 64))
PENDING_COLOR = Color.of((255, 214, 99))
EMBED_COLOR = Color.of((255, 214, 99))
INFISICAL_SDK = Infisical()


class ErrorCode(IntEnum):
    SUGGESTION_MESSAGE_DELETED = 1
    MISSING_PERMISSIONS = 2
    MISSING_SUGGESTIONS_CHANNEL = 3
    MISSING_LOG_CHANNEL = 4
    SUGGESTION_NOT_FOUND = 5
    OWNER_ONLY = 6
    SUGGESTION_CONTENT_TOO_LONG = 7
    INVALID_GUILD_CONFIG_CHOICE = 8
    COMMAND_ON_COOLDOWN = 9
    GENERIC_FORBIDDEN = 10
    UNHANDLED_ERROR = 11
    GENERIC_NOT_FOUND = 12
    CONFIGURED_CHANNEL_NO_LONGER_EXISTS = 13
    MISSING_FETCH_PERMISSIONS_IN_SUGGESTIONS_CHANNEL = 14
    MISSING_FETCH_PERMISSIONS_IN_LOGS_CHANNEL = 15
    MISSING_TRANSLATION = 16
    SUGGESTION_RESOLUTION_ERROR = 17
    MISSING_SEND_PERMISSIONS_IN_SUGGESTION_CHANNEL = 18
    MISSING_THREAD_CREATE_PERMISSIONS = 19
    QUEUE_IMBALANCE = 20
    MISSING_QUEUE_CHANNEL = 21
    BLOCKLISTED_USER = 22
    MISSING_QUEUE_LOG_CHANNEL = 23
    MISSING_PERMISSIONS_IN_QUEUE_CHANNEL = 24
    INVALID_FILE_TYPE = 25

    @classmethod
    def from_value(cls, value: int) -> ErrorCode:
        return ErrorCode(value)
